### PR TITLE
[Bug] Unhandled promise error

### LINKED ISSUE #11: Investigate unhandled promise rejections
Running the pdf2md converter throws a `UnhandledPromiseRejectionWarning: ReferenceError: document is not defined` error. This is hypothesised to be the cause of some font differences between the browser and the CLI version.

Investigate and solve the problem.

### PR DESCRIPTION
**Pull request by ricktjwong**
Fix the unhandled promise error by stubbing the document object. This document object does not exist in the CLI tool and causes pdfjs to raise an error.

This fix removes the error, but still fails to propagate the font information to include in the conversion. A new issue will be made to dig deeper.

Fixes #11

### CODE REVIEW

File: src/javascript/lib/pdf.jsx [hunk 1]
```diff
@@ -5,6 +5,10 @@ import Page from '../models/Page.jsx'
 
 const NO_OP = () => {}
 
+if (typeof document == "undefined") {
+  require('./domstubs.js').setStubs(global);
+}
```
Comment (LoneRifle) [inline src/javascript/lib/pdf.jsx]: I'd prefer to put this in `pdf2md.js`, since the stubbing concerns setting up the plumbing needed for the logic to work, not the logic itself

File: src/javascript/lib/domstubs.js [hunk 2]
```diff
@@ -0,0 +1,268 @@
...
+      console.assert(!(key in namespace), 'property should not be set: ' + key);
+      namespace[key] = exports[key];
+    });
+  };
+  exports.unsetStubs = function(namespace) {
+    exported_symbols.forEach(function(key) {
+      console.assert(key in namespace, 'property should be set: ' + key);
+      delete namespace[key];
+    });
+  };
```
Comment (LoneRifle) [inline src/javascript/lib/domstubs.js]: - do we really need the file in its entirety? surely we just need `document`? 
- attribution would be useful - add some jsdoc to indicate that this was taken from the node example of pdf.js

Comment (ricktjwong) [reply src/javascript/lib/domstubs.js]: Fair, I have removed the Image.prototype. The rest of the functions/objects: `xmlEncode`, `DOMElement`, `DOMElement.prototype` and `DOMElementSerializer` are part of the attributes of `document`, so I've left it there.

File: src/javascript/lib/pdf.jsx (hunk 1 above)
Comment (ricktjwong) [reply src/javascript/lib/pdf.jsx]: Agreed, makes sense.
